"""Initial migration

Revision ID: 12bc798a468d
Revises: 81c11b0939e8
Create Date: 2024-10-20 22:44:28.058070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bc798a468d'
down_revision: Union[str, None] = '81c11b0939e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('session_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_accounts', 'session_data')
    # ### end Alembic commands ###
