"""Added account_number

Revision ID: 2223fd470537
Revises: ec994a4a523f
Create Date: 2024-10-21 06:18:20.789879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2223fd470537'
down_revision: Union[str, None] = 'ec994a4a523f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('account_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_accounts', 'account_number')
    # ### end Alembic commands ###
