"""Add proxy column to TwitterAccount

Revision ID: 41dffc65aa9f
Revises: 2223fd470537
Create Date: 2024-10-22 19:26:35.670520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dffc65aa9f'
down_revision: Union[str, None] = '2223fd470537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('proxy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_accounts', 'proxy')
    # ### end Alembic commands ###
