"""Added max_accounts

Revision ID: 46ae479964ba
Revises: 41dffc65aa9f
Create Date: 2024-10-27 22:52:28.165943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ae479964ba'
down_revision: Union[str, None] = '41dffc65aa9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_twitter_accounts_id', table_name='twitter_accounts')
    op.drop_table('twitter_accounts')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('twitter_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('twitter_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sandbox_login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sandbox_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('ep_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owns_alphapass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proxy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='twitter_accounts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='twitter_accounts_pkey')
    )
    op.create_index('ix_twitter_accounts_id', 'twitter_accounts', ['id'], unique=False)
    # ### end Alembic commands ###
