"""Initial migration

Revision ID: 4ad3a2508a33
Revises: 1e0033389d81
Create Date: 2024-10-19 06:31:27.450634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad3a2508a33'
down_revision: Union[str, None] = '1e0033389d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('twitter_token', sa.String(), nullable=False))
    op.add_column('twitter_accounts', sa.Column('sandbox_cookie', sa.String(), nullable=False))
    op.drop_column('twitter_accounts', 'access_token_secret')
    op.drop_column('twitter_accounts', 'consumer_key')
    op.drop_column('twitter_accounts', 'consumer_secret')
    op.drop_column('twitter_accounts', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('twitter_accounts', sa.Column('consumer_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('twitter_accounts', sa.Column('consumer_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('twitter_accounts', sa.Column('access_token_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('twitter_accounts', 'sandbox_cookie')
    op.drop_column('twitter_accounts', 'twitter_token')
    # ### end Alembic commands ###
