"""Initial migration

Revision ID: 4ae6e1c16ab3
Revises: 4ad3a2508a33
Create Date: 2024-10-20 08:21:00.833052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae6e1c16ab3'
down_revision: Union[str, None] = '4ad3a2508a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('sandbox_login', sa.String(), nullable=False, server_default='default_login'))
    op.add_column('twitter_accounts', sa.Column('sandbox_password', sa.String(), nullable=False, server_default='default_password'))
    op.drop_column('twitter_accounts', 'sandbox_cookie')

    # Remove default for new columns after adding them
    op.alter_column('twitter_accounts', 'sandbox_login', server_default=None)
    op.alter_column('twitter_accounts', 'sandbox_password', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('sandbox_cookie', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('twitter_accounts', 'sandbox_password')
    op.drop_column('twitter_accounts', 'sandbox_login')
    # ### end Alembic commands ###
